language: ruby
rvm:
  - 1.9.3
  - 2.2.3
# https://github.com/heroku/heroku/pull/858
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"
